all:
	g++ Trees.cpp Input.cpp Main.cpp -o output/a -Wall -Werror -Wextra && ./output/a

debug:
	g++ Trees.cpp  Input.cpp Main.cpp -g -o output/a -Wall -Werror -Wextra && ./output/a 


run :
	gdb ./output/a